name: Devmem2 Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: install
      run: sudo apt-get -y install g++

    - name: compile
      run: g++ main.cpp

    - name: check executable
      run: ./a.out
